MONGODB_HOST: mongodb.gokul.fun
REDIS_HOST: redis.gokul.fun
CATALOGUE_HOST: catalogue.gokul.fun
CART_HOST: cart.gokul.fun
MYSQL_HOST: mysql.gokul.fun
RABBITMQ_HOST: rabbitmq.gokul.fun
USER_HOST: user.gokul.fun
SHIPPING_HOST: shipping.gokul.fun
PAYMENT_HOST: payment.gokul.fun
